config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
}


  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_scope :customer do
    post "customers/guest_sign_in", to: "public/sessions#guest_sign_in"
    post "customers/sign_up", to: "public/registrations#create"
  end

  scope module: :public do
    root to: "homes#top"
    get "about" => "homes#about", as: "about"
    get "item/:id" => "items#show", as: "item"
    get "items" => "items#index", as: "items"
    get "comments/:id/edit" => "customers#comments", as: "comments_edit"
    get "comments" => "customers#comments", as: "comments"

    resources :items do
      resources :comments
    end


    delete "cart_item/destroy_all" => "cart_items#destroy_all"
    post "cart_items/confirm" => "cart_items#confirm", as: "cart_items_confirm"
    resources :cart_items

    get "customers/information/edit" => "customers#edit", as: "edit_customers"
    get "customers/unsubscribe" => "customers#unsubscribe", as: "customer_unsubscribe"
    patch "customers/update" => "customers#update", as: "customer_update"
    patch "customers/withdrawal" => "customers#withdrawal", as: "customer_withdrawal"
    resource :customers, only: [:show]

    post "orders/confirm" => "orders#confirm", as: "orders_confirm"
    get "orders/complete" => "orders#complete", as: "orders_complete"
    resources :orders
  end

  namespace :admin do
    root to: "homes#top"
    resources :customers
    get "comments" => "customers#comments", as: "customer_comments"
    resources :comments

    resources :orders do
    resources :order_details
  end

    resources :items
  end
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  has_many :comments, dependent: :destroy

  def with_tax_price
    (price * 1.1).floor
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_items_path
  end

  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path
  end

  private
    def item_params
      params.require(:item).permit(:name, :introduction, :price, :is_active, :image)
    end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="font-weight-bold h2 mt-5 mb-5 text-center">
    商品編集
  </div>
<div class="row justify-content-center">
  <%= form_with model: @item, url: admin_item_path, method: :patch do |f| %>
    <table class="table table-borderless">
      <tr>
          <td>商品画像</td>
          <td><%= f.file_field :image, accept: "image/*" %></td>
      </tr>
      <tr>
          <td>商品名</td>
          <td><%= f.text_field :name %></td>
      </tr>
      <tr>
          <td>商品説明</td>
          <td><%= f.text_area :introduction, :size => "30x5"%></td>
      </tr>
      <tr>
          <td>税抜価格</td>
          <td><%= f.text_field :price, :placeholder => "1000" %>円</td>
      </tr>
      <tr>
          <td>販売ステータス</td>
          <td>
            <% @item.is_active %>
            <%= f.radio_button :is_active, :true %>
            販売中
            <%= f.radio_button :is_active, :false %>
            販売停止中
          </td>
      </tr>
</div>
    </table>
        <div class="text-center">
          <%= f.submit "変更を保存", class: "btn btn-lg btn-success"  %>
        </div>
    <% end %>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="text-center">
    <div class="font-weight-bold h2 mt-5 mb-5">
    商品一覧
    </div>
    <div class="text-left mb-5 pl-5">
      <%= link_to "商品新規登録", new_admin_item_path(@items), class: "btn btn-info rounded-5" %>
    </div>
    <table class="table table-bordered">
      <th>商品ID</th><th>商品名</th><th>税抜価格</th>
      <% @items.each do |item| %>
      <tr>
        <td><%= item.id %></td>
        <td><%= link_to item.name, admin_item_path(item) %></td>
        <td>¥<%= item.price %></td>
      </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="text-center">
    <div class="font-weight-bold h2 mt-5 mb-5">
    商品新規登録
    </div>
  </div>
  <div class="row justify-content-center">
  <%= form_with model: @item, url: admin_items_path, method: :post do |f| %>
<table class="table table-borderless">
  <tr>
    <td>商品画像</td>
     <td><%= f.file_field :image, accept: "image/*" %></td>
    </tr>
   <tr>
<td>商品名</td>
  <td><%= f.text_field :name %></td>
   </tr>
     <tr>
      <td>商品説明</td>
    <td><%= f.text_area :introduction, :size => "30x5"%></td>
   </tr>
    <tr>
     <td>税抜価格</td>
    <td><%= f.text_field :price, :placeholder => "1000" %>円</td>
   </tr>
  <tr>
<td>販売ステータス</td>
  <td><%= f.radio_button :is_active, :true %>
    <label>販売中</label>
      <%= f.radio_button :is_active, :false %>
    <label>販売停止中</label>
   </td>
  </tr>
</table>
 <div class="text-center">
  <%= f.submit "新規登録", class: "btn btn-success btn-lg" %>
   </div>
    </div>
    <% end %>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="font-weight-bold h2 mt-5 mb-5 text-center">
    商品詳細
  </div>
    <div class="row justify-content-center">
      <div class="col-md-3">
        <% if @item.image.attached? %>
        <%= image_tag @item.image, size: "250x350" %>
        <% else %>
        <%= image_tag 'no_image.jpg', size: "200x200" %>
        <% end %>
      </div>
    <div class="col-md-8">
      <table class="table table-borderless">
        <tr>
          <th>商品名</th>
            <td><%= @item.name %></td>
        </tr>
        <tr>
          <th>商品説明</th>
            <td><%= simple_format(@item.introduction) %></td>
        </tr>
        <tr>
          <th>税込価格</th>
            <td><%= @item.with_tax_price %>円</td>
        </tr>
        <tr>
          <th>販売ステータス</th>
            <td><% if @item.is_active == true %>
                  販売中
                <% else %>
                  販売停止中
                <% end %>
            </td>
        </tr>
      </table>
      <div class="text-center">
        <td><%= link_to "編集する", edit_admin_item_path(@item), class: "btn btn-success w-50 mt-5" %></td>
      </div>
    </div>
    </div>
</div>