config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
}


  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_scope :customer do
    post "customers/guest_sign_in", to: "public/sessions#guest_sign_in"
    post "customers/sign_up", to: "public/registrations#create"
  end

  scope module: :public do
    root to: "homes#top"
    get "about" => "homes#about", as: "about"
    get "item/:id" => "items#show", as: "item"
    get "items" => "items#index", as: "items"
    get "comments/:id/edit" => "customers#comments", as: "comments_edit"
    get "comments" => "customers#comments", as: "comments"

    resources :items do
      resources :comments
    end


    delete "cart_item/destroy_all" => "cart_items#destroy_all"
    post "cart_items/confirm" => "cart_items#confirm", as: "cart_items_confirm"
    resources :cart_items

    get "customers/information/edit" => "customers#edit", as: "edit_customers"
    get "customers/unsubscribe" => "customers#unsubscribe", as: "customer_unsubscribe"
    patch "customers/update" => "customers#update", as: "customer_update"
    patch "customers/withdrawal" => "customers#withdrawal", as: "customer_withdrawal"
    resource :customers, only: [:show]

    post "orders/confirm" => "orders#confirm", as: "orders_confirm"
    get "orders/complete" => "orders#complete", as: "orders_complete"
    resources :orders
  end

  namespace :admin do
    root to: "homes#top"
    resources :customers
    get "comments" => "customers#comments", as: "customer_comments"
    resources :comments

    resources :orders do
    resources :order_details
  end

    resources :items
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, presence: true, format: { with: /\A[ｧ-ﾝﾞﾟァ-ヶー－]+\z/,message: "全角カタカナのみで入力して下さい" }
  validates :last_name_kana, presence: true, format: { with: /\A[ｧ-ﾝﾞﾟァ-ヶー－]+\z/,message: "全角カタカナのみで入力して下さい" }
  validates :postal_code, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}
  validates :address, presence: true
  validates :telephone_number, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}
  validates :password, presence: true, confirmation: true, length: { minimum: 6 }, on: :create
  validates :password_confirmation, confirmation: true, on: :create



  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :comments, dependent: :destroy

  # ログイン時に退会済みのユーザーが同じアカウントでログイン出来ないようにするする制約。
  def active_for_authentication?
    super && (is_deleted == false)
  end


  def full_name
    self.last_name + self.first_name
  end

  def full_name_kana
    self.last_name_kana + self.first_name_kana
  end

  def self.guest
    find_or_create_by!(email: "guest2@test.com") do |user|
      user.password = SecureRandom.urlsafe_base64 # ランダムなパスワードを生成
      user.last_name = "ゲスト"
      user.first_name = "ゲスト"
      user.last_name_kana = "ゲスト"
      user.first_name_kana = "ゲスト"
      user.postal_code = "0000000"
      user.address = "大阪府"
      user.telephone_number = "00000000000"
    end
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def new
    @customers = Customer.new
  end

  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      bypass_sign_in(@customer)
      redirect_to admin_customer_path(@customer.id)
    else
      render "edit"
    end
  end

  def comments
    @comments = Comment.all
  end

  private
    def customer_params
      params.require(:customer).permit(:first_name, :last_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number, :is_deleted)
    end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/comments.html.erb
<div class="container">
  <div class="font-weight-bold h2 mt-5 mb-5 text-center">
    口コミ一覧
  </div>
    <div class="row">
      <% @comments.each do |comment| %>
      <div class="col-md-12 mt-3">
        <div class="border border-dark w-50 p-4 mx-auto ">
        <div id="post_raty<%= comment.id %>"></div>
          <script>
          var elem = document.getElementById('post_raty<%= comment.id %>');
          var opt = {
              starOn: "<%= asset_path('star-on.png') %>",
              starOff: "<%= asset_path('star-off.png') %>",
              starHalf: "<%= asset_path('star-half.png') %>",
              half: true,
              readOnly: true,
              score: <%= comment.star || 0 %>
            };
            raty(elem,opt);
          </script>
          <%= comment.created_at.strftime('%Y/%m/%d') %></br>
          会員No.<%= comment.customer.id %>
          <%= comment.customer.full_name %></br>
          <%= comment.review %></br>
          <%= image_tag comment.item.image, size: "250x200", class: "mt-3 mb-3" %></br>
          <%= comment.item.name %>
          <%= link_to "編集", edit_admin_comment_path(comment), class: "text-right" %>
        </div>
      </div>
      <% end %>
  </div>
</div>

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="font-weight-bold h2 mt-5 mb-5 text-center">
    会員情報編集
  </div>
  <%if @customer.errors.any? %>
    <%= @customer.errors.count %>件のエラーが発生しました
      <% @customer.errors.full_messages.each do |message| %>
       <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <div class="row justify-content-center">
    <%= form_with model: @customer, url: admin_customer_path, method: :patch do |f| %>
      <table class="table table-borderless">
    <tr>
        <td class="text-left">氏名</td>
        <td class="text-left"><%= f.text_field :last_name, class: "col-auto" %>
        <%= f.text_field :first_name, class: "col-auto" %></td>
    </tr>
    <tr>
        <td class="text-left">フリガナ</td>
        <td class="text-left"><%= f.text_field :last_name_kana, class: "col-auto" %>
        <%= f.text_field :first_name_kana, class: "col-auto" %></td>
    </tr>
    <tr>
        <td class="text-left">メールアドレス</td>
        <td class="text-left"><%= f.email_field :email, class: "col-auto", autofocus: true, autocomplete: "email" %></td>
    </tr>
    <tr>
        <td class="text-left">郵便番号</td>
        <td class="text-left"><%= f.text_field :postal_code, class: "col-auto", autofocus: true, autocomplete: "postal_code" %></td>
    </tr>
    <tr>
        <td class="text-left">住所</td>
        <td class="text-left"><%= f.text_field :address, class: "col-auto", autofocus: true, autocomplete: "address" %></td>
    </tr>
    <tr>
        <td class="text-left">電話番号(ハイフン無し)</td>
        <td class="text-left"><%= f.text_field :telephone_number, class: "col-auto" %></td>
    </tr>
    <tr>
        <td class="text-left">会員ステータス</td>
        <td class="text-left">
          <%= f.radio_button :is_deleted, 'false' %>
          有効
          <%= f.radio_button :is_deleted, 'true' %>
          退会
        </td>
    </tr>
  </div>
      </table>
        <div class="text-center">
          <%= f.submit "変更を保存", class: "btn btn-lg btn-success"  %>
        </div>
  <% end %>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="text-center">
    <div class="font-weight-bold h2 mt-5 mb-5">
    会員一覧
    </div>
      <div class="text-left mb-3">
        <%= link_to "商品レビュー履歴", admin_customer_comments_path(@comments), class: "btn btn-outline-info" %>
      </div>
      <table class="table table-bordered mb-5">
        <th class="col-md-2">会員ID</th>
        <th class="col-md-4">氏名</th>
        <th class="col-md-2">メールアドレス</th>
      <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.id %></td>
        <td><%= link_to customer.full_name, admin_customer_path(customer) %></td>
        <td><%= customer.email %></td>
      </tr>
      <% end %>
      </table>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="col-md-8 h5 mt-5 mb-5">
    <%= @customer.full_name %>さんの会員詳細
  </div>
      <div class="row justify-content-center">
        <table class="table table-bordered w-50">
          <tr>
              <th class="col-md-2">会員ID</th>
              <td class="col-md-3"><%= @customer.id %></td>
          </tr>
          <tr>
              <th>氏名</th>
              <td><%= @customer.full_name %></td>
          </tr>
          <tr>
              <th>フリガナ</th>
              <td><%= @customer.full_name_kana %></td>
          </tr>
          <tr>
              <th>郵便番号</th>
              <td><%= @customer.postal_code %></td>
          </tr>
          <tr>
              <th>住所</th>
              <td><%= @customer.address %></td>
          </tr>
          <tr>
              <th>電話番号</th>
              <td><%= @customer.telephone_number %></td>
          </tr>
          <tr>
              <th>メールアドレス</th>
              <td><%= @customer.email %></td>
          </tr>
          <tr>
              <th>会員ステータス</th>
              <td><% if @customer.is_deleted == true %>
                    退会
                  <% else %>
                    有効
                  <% end %>
              </td>
          </tr>
        </table>
    </div>
    <div class="text-center">
      <td><%= link_to "編集する", edit_admin_customer_path(@customer), class: "btn btn-info w-50 mt-5 mb-5" %></td>
    </div>
</div>