config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
}


  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_scope :customer do
    post "customers/guest_sign_in", to: "public/sessions#guest_sign_in"
    post "customers/sign_up", to: "public/registrations#create"
  end

  scope module: :public do
    root to: "homes#top"
    get "about" => "homes#about", as: "about"
    get "item/:id" => "items#show", as: "item"
    get "items" => "items#index", as: "items"
    get "comments/:id/edit" => "customers#comments", as: "comments_edit"
    get "comments" => "customers#comments", as: "comments"

    resources :items do
      resources :comments
    end


    delete "cart_item/destroy_all" => "cart_items#destroy_all"
    post "cart_items/confirm" => "cart_items#confirm", as: "cart_items_confirm"
    resources :cart_items

    get "customers/information/edit" => "customers#edit", as: "edit_customers"
    get "customers/unsubscribe" => "customers#unsubscribe", as: "customer_unsubscribe"
    patch "customers/update" => "customers#update", as: "customer_update"
    patch "customers/withdrawal" => "customers#withdrawal", as: "customer_withdrawal"
    resource :customers, only: [:show]

    post "orders/confirm" => "orders#confirm", as: "orders_confirm"
    get "orders/complete" => "orders#complete", as: "orders_complete"
    resources :orders
  end

  namespace :admin do
    root to: "homes#top"
    resources :customers
    get "comments" => "customers#comments", as: "customer_comments"
    resources :comments

    resources :orders do
    resources :order_details
  end

    resources :items
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { credit_card: 0, transfer: 1 }

  enum order_status: { waiting_for_payment: 0, payment_confirmation: 1, preparing_to_ship: 2, sent: 3 }

  has_one_attached :image

  belongs_to :customer
  has_many :order_details, dependent: :destroy


  def address_display
    "〒" + postal_code + " " + address + " " + name
  end

  def full_name
    self.last_name + self.first_name
  end

  def full_name_kana
    self.last_name_kana + self.first_name_kana
  end

  def subtotal
    item.with_tax_price * amount
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @customer = @order.customer
    @total = 0
  end


  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    redirect_to admin_order_path(@order.id)
  end


  private
    def order_params
      params.require(:order).permit(:customer_id, :item_id, :tax_included_price, :amount, :making_status, :payment_method, :order_status, :image)
    end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="font-weight-bold h2 mt-5 mb-5 text-center">
    <%= @customer.full_name%>さんの注文履歴詳細
  </div>
  <div class="row pr-5 border-bottom">
    <div class="col-md-4"></div>
      <div class="col-md-3 font-weight-bold">購入者</div>
        <div class="col-md-3 mb-3">
          <%= @order.customer.full_name %>
        </div>
    <div class="col-md-4"></div>
      <div class="col-md-3 font-weight-bold">注文日</div>
        <div class="col-md-3 mb-3">
          <%= @order.created_at.strftime('%Y/%m/%d') %>
        </div>
    <div class="col-md-4"></div>
      <div class="col-md-3 font-weight-bold">配送先</div>
        <div class="col-md-3 mb-3">
          〒<%= @order.postal_code %>
          <%= @order.address %></br>
          <%= @order.name %>
        </div>
    <div class="col-md-4"></div>
      <div class="col-md-3 font-weight-bold">支払い方法</div>
        <div class="col-md-3 mb-3">
          <%= @order.payment_method_i18n %>
        </div>
    <div class="col-md-4"></div>
      <div class="col-md-3 font-weight-bold">注文ステータス</div>
        <div class="col-md-3 mb-3">
          <%= form_with model: @order, url: admin_order_path, method: :patch do |f| %>
            <%= f.select :order_status, Order.order_statuses.keys.map {|k| [I18n.t("enums.order.order_status.#{k}"), k]} %>
            <%= f.submit "更新", class:"btn btn-sm btn-success" %>
          <% end %>
        </div>
  </div>
  <% sum = 0 %>
  <% @order_details.each do |order_detail| %>
    <%= form_with model: order_detail, url: admin_order_order_detail_path(@order,order_detail) do |f| %>
    <div class="row mt-3">
      <div class="col-md-2"></div>
        <%= image_tag order_detail.item.image, size: "150x150" %>
      <div class="col-md-3 mt-3">
        <%= order_detail.item.name %></br>
        &yen;<%= order_detail.item.with_tax_price %></br>
        数量 <%= order_detail.amount %></br>
      </div>
    <% sum = sum + order_detail.item.with_tax_price*order_detail.amount %>
    </div>
    <% end %>
  <% end %>
    <div class="float-right">
  <table class ="table-sm table-borderless">
    <tr>
      <th>商品合計</th>
      <td><%= sum %></td>
    </tr>
    <tr>
      <th>送料</th>
      <td><%= POSTAGE %></td>
    </tr>
    <tr>
      <th>お支払い金額</th>
      <td><%= sum + POSTAGE %></td>
    </tr>
  </table>
  </div>
</div>