config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
}


  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_scope :customer do
    post "customers/guest_sign_in", to: "public/sessions#guest_sign_in"
    post "customers/sign_up", to: "public/registrations#create"
  end

  scope module: :public do
    root to: "homes#top"
    get "about" => "homes#about", as: "about"
    get "item/:id" => "items#show", as: "item"
    get "items" => "items#index", as: "items"
    get "comments/:id/edit" => "customers#comments", as: "comments_edit"
    get "comments" => "customers#comments", as: "comments"

    resources :items do
      resources :comments
    end


    delete "cart_item/destroy_all" => "cart_items#destroy_all"
    post "cart_items/confirm" => "cart_items#confirm", as: "cart_items_confirm"
    resources :cart_items

    get "customers/information/edit" => "customers#edit", as: "edit_customers"
    get "customers/unsubscribe" => "customers#unsubscribe", as: "customer_unsubscribe"
    patch "customers/update" => "customers#update", as: "customer_update"
    patch "customers/withdrawal" => "customers#withdrawal", as: "customer_withdrawal"
    resource :customers, only: [:show]

    post "orders/confirm" => "orders#confirm", as: "orders_confirm"
    get "orders/complete" => "orders#complete", as: "orders_complete"
    resources :orders
  end

  namespace :admin do
    root to: "homes#top"
    resources :customers
    get "comments" => "customers#comments", as: "customer_comments"
    resources :comments

    resources :orders do
    resources :order_details
  end

    resources :items
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheCosmetic</title>

    <script src="https://kit.fontawesome.com/3e48c8f6cb.js" crossorigin="anonymous"></script>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<header>
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <div class="card1">
          <%= image_tag asset_path('pink.jpg'), alt: '', class: "card-img" %>
           <div class="card-img-overlay">
            <div class="display-2">The Cosmetic</div>
           </div>
        </div>
      </div>
    </div>
  <div class="menu">
<%= link_to "Home","/",class:"fa-solid fa-house text-decoration-none text-secondary mt-5" %>
  </div>
    <div class="text-center mt-4 mb-4">
      <% if admin_signed_in? %>
        <div class="menu">
          <%= link_to "Items", admin_items_path, class: "text-decoration-none text-secondary mr-5" %>
          <%= link_to "Customers", admin_customers_path, class: "text-decoration-none text-secondary mr-5" %>
          <%= link_to "Orders", admin_root_path, class: "text-decoration-none text-secondary mr-5" %>
          <%= link_to 'Log out', destroy_admin_session_path, method: :delete, class: "text-decoration-none text-secondary mr-5" %>
        </div>
      <% elsif customer_signed_in? %>
        <div class="menu">
          <%= link_to "My page", customers_path, class: "text-decoration-none text-secondary mr-5" %>
          <%= link_to "Items", items_path, class: "text-decoration-none text-secondary mr-5" %>
          <%= link_to "review", comments_path, class: "text-decoration-none text-secondary mr-5" %>
          <%= link_to "Cart Item", cart_items_path, class: "text-decoration-none text-secondary mr-5" %>
          <%= link_to 'Log out', destroy_customer_session_path, method: :delete, class: "text-decoration-none text-secondary mr-5" %>
        </div>
      <% else %>
        <div class="menu">
          <%= link_to "About", about_path, class: "text-decoration-none text-secondary mr-5" %>
          <%= link_to "Items", items_path, class: "text-decoration-none text-secondary mr-5" %>
          <%= link_to "Sign up", new_customer_registration_path, class: "text-decoration-none text-secondary mr-5" %>
          <%= link_to "Log in", new_customer_session_path, class: "text-decoration-none text-secondary mr-5" %>
          <%= link_to "Guest Login", customers_guest_sign_in_path, method: :post, class: "text-decoration-none text-secondary" %>
        </div>
      <% end %>
    </div>
    </div>
</header>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<%= yield %>
</body>
</html>
<footer>
  <div class="mt-5"></div>
</footer>